-- MySQL Script generated by MySQL Workbench
-- Thu Nov  1 19:10:25 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema BDARCO
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema BDARCO
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BDARCO` DEFAULT CHARACTER SET utf8 ;
USE `BDARCO` ;

-- -----------------------------------------------------
-- Table `BDARCO`.`DOCENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDARCO`.`DOCENTE` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `FORMACAO` VARCHAR(45) NOT NULL,
  `NOME` VARCHAR(45) NOT NULL,
  `EMAIL` VARCHAR(45) NOT NULL,
  `SENHA` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `BDARCO`.`ARCO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDARCO`.`ARCO` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `STATUS` INT(11) NOT NULL,
  `NOME` VARCHAR(45) NOT NULL,
  `DOCENTE_ID` INT(11) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_ARCO_DOCENTE1_idx` (`DOCENTE_ID` ASC),
  CONSTRAINT `fk_ARCO_DOCENTE1`
    FOREIGN KEY (`DOCENTE_ID`)
    REFERENCES `BDARCO`.`DOCENTE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `BDARCO`.`AREALIDADE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDARCO`.`AREALIDADE` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `RESUMO` TEXT NOT NULL,
  `STATUS` INT(11) NOT NULL,
  `ARCO_ID` INT(11) NOT NULL,
  `NOME` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  PRIMARY KEY (`ID`, `ARCO_ID`),
  INDEX `fk_AREALIDADE_ARCO1_idx` (`ARCO_ID` ASC),
  CONSTRAINT `fk_AREALIDADE_ARCO1`
    FOREIGN KEY (`ARCO_ID`)
    REFERENCES `BDARCO`.`ARCO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `BDARCO`.`DISCENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDARCO`.`DISCENTE` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `INSTITUICAO` VARCHAR(45) NOT NULL,
  `NOME` VARCHAR(45) NOT NULL,
  `EMAIL` VARCHAR(45) NOT NULL,
  `SENHA` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `BDARCO`.`DOCUMENTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDARCO`.`DOCUMENTO` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(45) NOT NULL,
  `CAMINHO` VARCHAR(45) NOT NULL,
  `IDETAPA` INT(11) NOT NULL,
  `ARCO_ID` INT(11) NOT NULL,
  PRIMARY KEY (`ID`, `ARCO_ID`),
  INDEX `fk_DOCUMENTO_ARCO1_idx` (`ARCO_ID` ASC),
  CONSTRAINT `fk_DOCUMENTO_ARCO1`
    FOREIGN KEY (`ARCO_ID`)
    REFERENCES `BDARCO`.`ARCO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `BDARCO`.`GRUPO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDARCO`.`GRUPO` (
  `DISCENTE_ID` INT(11) NOT NULL,
  `NOME` VARCHAR(45) NOT NULL,
  `ARCO_ID` INT(11) NOT NULL,
  PRIMARY KEY (`DISCENTE_ID`, `ARCO_ID`),
  INDEX `fk_GRUPO_DISCENTE1_idx` (`DISCENTE_ID` ASC),
  INDEX `fk_GRUPO_ARCO1_idx` (`ARCO_ID` ASC),
  CONSTRAINT `fk_GRUPO_DISCENTE1`
    FOREIGN KEY (`DISCENTE_ID`)
    REFERENCES `BDARCO`.`DISCENTE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_GRUPO_ARCO1`
    FOREIGN KEY (`ARCO_ID`)
    REFERENCES `BDARCO`.`ARCO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `BDARCO`.`HSOLUCAO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDARCO`.`HSOLUCAO` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `RESUMO` TEXT NOT NULL,
  `STATUS` INT(11) NOT NULL,
  `ARCO_ID` INT(11) NOT NULL,
  `NOME` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  PRIMARY KEY (`ID`, `ARCO_ID`),
  INDEX `fk_HSOLUCAO_ARCO1_idx` (`ARCO_ID` ASC),
  CONSTRAINT `fk_HSOLUCAO_ARCO1`
    FOREIGN KEY (`ARCO_ID`)
    REFERENCES `BDARCO`.`ARCO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `BDARCO`.`MENSAGEM`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDARCO`.`MENSAGEM` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `TEXTO` VARCHAR(45) NOT NULL,
  `IDAUTOR` INT(11) NOT NULL,
  `DATA` DATETIME NOT NULL,
  `ARCO_ID` INT(11) NOT NULL,
  PRIMARY KEY (`ID`, `ARCO_ID`),
  INDEX `fk_MENSAGEM_ARCO1_idx` (`ARCO_ID` ASC),
  CONSTRAINT `fk_MENSAGEM_ARCO1`
    FOREIGN KEY (`ARCO_ID`)
    REFERENCES `BDARCO`.`ARCO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `BDARCO`.`OBSREALIDADE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDARCO`.`OBSREALIDADE` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `RESUMO` TEXT NOT NULL,
  `STATUS` INT(11) NOT NULL,
  `ARCO_ID` INT(11) NOT NULL,
  `NOME` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  PRIMARY KEY (`ID`, `ARCO_ID`),
  INDEX `fk_OBSREALIDADE_ARCO_idx` (`ARCO_ID` ASC),
  CONSTRAINT `fk_OBSREALIDADE_ARCO`
    FOREIGN KEY (`ARCO_ID`)
    REFERENCES `BDARCO`.`ARCO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `BDARCO`.`PTOCHAVE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDARCO`.`PTOCHAVE` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `RESUMO` TEXT NOT NULL,
  `STATUS` INT(11) NOT NULL,
  `ARCO_ID` INT(11) NOT NULL,
  `NOME` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  PRIMARY KEY (`ID`, `ARCO_ID`),
  INDEX `fk_PTOCHAVE_ARCO1_idx` (`ARCO_ID` ASC),
  CONSTRAINT `fk_PTOCHAVE_ARCO1`
    FOREIGN KEY (`ARCO_ID`)
    REFERENCES `BDARCO`.`ARCO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `BDARCO`.`TEORIZACAO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDARCO`.`TEORIZACAO` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `RESUMO` TEXT NOT NULL,
  `STATUS` INT(11) NOT NULL,
  `ARCO_ID` INT(11) NOT NULL,
  `NOME` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  PRIMARY KEY (`ID`, `ARCO_ID`),
  INDEX `fk_TEORIZACAO_ARCO1_idx` (`ARCO_ID` ASC),
  CONSTRAINT `fk_TEORIZACAO_ARCO1`
    FOREIGN KEY (`ARCO_ID`)
    REFERENCES `BDARCO`.`ARCO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
