-- MySQL Script generated by MySQL Workbench
-- Fri Jan 11 17:19:50 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bdarco
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bdarco
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bdarco` DEFAULT CHARACTER SET utf8 ;
USE `bdarco` ;

-- -----------------------------------------------------
-- Table `bdarco`.`arco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdarco`.`arco` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `STATUS` VARCHAR(45) NOT NULL,
  `NOME` VARCHAR(45) NOT NULL,
  `ID_CRIADOR` INT(11) NOT NULL,
  `DOCENTE_ID` INT(11) NOT NULL,
  `COMPARTILHADO` INT(11) NOT NULL DEFAULT '1',
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bdarco`.`discente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdarco`.`discente` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `INSTITUICAO` VARCHAR(45) NULL,
  `NOME` VARCHAR(45) NULL,
  `EMAIL` VARCHAR(45) NULL,
  `SENHA` VARCHAR(45) NULL,
  `FOTO` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bdarco`.`docente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdarco`.`docente` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `FORMACAO` VARCHAR(45) NULL,
  `NOME` VARCHAR(45) NULL,
  `EMAIL` VARCHAR(45) NULL,
  `SENHA` VARCHAR(45) NULL,
  `FOTO` VARCHAR(256) NULL ,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bdarco`.`documento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdarco`.`documento` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `NOME` TEXT NULL,
  `CAMINHO` TEXT NULL,
  `ETAPA_ID` INT(11) NULL,
  `ARCO_ID` INT(11) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bdarco`.`etapa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdarco`.`etapa` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(45) NULL,
  `RESUMO` TEXT NULL,
  `STATUS` VARCHAR(45) NULL,
  `ARCO_ID` INT(11) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bdarco`.`generate_id`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdarco`.`generate_id` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(256) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bdarco`.`grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdarco`.`grupo` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(45) NULL,
  `DISCENTE_ID` INT(11) NULL,
  `ARCO_ID` INT(11) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bdarco`.`mensagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdarco`.`mensagem` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `TEXTO` VARCHAR(45) NULL,
  `IDAUTOR` INT(11) NULL,
  `DATA` DATETIME NULL,
  `ARCO_ID` INT(11) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bdarco`.`solicitacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdarco`.`solicitacao` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `ARCO_ID` INT(11) NOT NULL,
  `DOCENTE_ID` INT(11) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

USE `bdarco` ;

-- -----------------------------------------------------
-- procedure verificar_completo
-- -----------------------------------------------------

DELIMITER $$
USE `bdarco`$$
CREATE DEFINER=`root`@`%` PROCEDURE `verificar_completo`(arco_id int)
BEGIN
   IF(select count(BDARCO.ETAPA.STATUS)
	from BDARCO.ETAPA
	where BDARCO.ETAPA.ARCO_ID = arco_id
	AND BDARCO.ETAPA.STATUS = 1 
    having count(BDARCO.ETAPA.STATUS) = 5)
    
    then 
        UPDATE ARCO SET STATUS = 'CONCLUÍDO' WHERE ID = arco_id;
    else 
		select 'NÃO ESTÁ COMPLETO' as Msg;
    END IF;
    
END$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
